//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyStore.Client.OrderServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SupplierDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CandyStore.Client.OrderServiceProxy.ProductDto[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CandyStore.Client.OrderServiceProxy.ProductDto[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private decimal PriceField;
        
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IdentificationNumber {
            get {
                return this.IdentificationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationNumberField, value) != true)) {
                    this.IdentificationNumberField = value;
                    this.RaisePropertyChanged("IdentificationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierField;
        
        private System.DateTime OrderedDateField;
        
        private System.DateTime ExpectedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CandyStore.Client.OrderServiceProxy.ProductDto[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime OrderedDate {
            get {
                return this.OrderedDateField;
            }
            set {
                if ((this.OrderedDateField.Equals(value) != true)) {
                    this.OrderedDateField = value;
                    this.RaisePropertyChanged("OrderedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime ExpectedDate {
            get {
                return this.ExpectedDateField;
            }
            set {
                if ((this.ExpectedDateField.Equals(value) != true)) {
                    this.ExpectedDateField = value;
                    this.RaisePropertyChanged("ExpectedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CandyStore.Client.OrderServiceProxy.ProductDto[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceProxy.OrderServiceSoap")]
    public interface OrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllSuppliersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSuppliers", ReplyAction="*")]
        CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponse GetAllSuppliers(CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSuppliers", ReplyAction="*")]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponse> GetAllSuppliersAsync(CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest request);
        
        // CODEGEN: Generating message contract since element name supplierName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsBySupplier", ReplyAction="*")]
        CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponse GetProductsBySupplier(CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsBySupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponse> GetProductsBySupplierAsync(CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest request);
        
        // CODEGEN: Generating message contract since element name customer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByCustomer", ReplyAction="*")]
        CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponse GetOrdersByCustomer(CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponse> GetOrdersByCustomerAsync(CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name customer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        CandyStore.Client.OrderServiceProxy.PlaceOrderResponse PlaceOrder(CandyStore.Client.OrderServiceProxy.PlaceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.PlaceOrderResponse> PlaceOrderAsync(CandyStore.Client.OrderServiceProxy.PlaceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloseOrder", ReplyAction="*")]
        void CloseOrder(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloseOrder", ReplyAction="*")]
        System.Threading.Tasks.Task CloseOrderAsync(int orderId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSuppliersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSuppliers", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequestBody Body;
        
        public GetAllSuppliersRequest() {
        }
        
        public GetAllSuppliersRequest(CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSuppliersRequestBody {
        
        public GetAllSuppliersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSuppliersResponse", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponseBody Body;
        
        public GetAllSuppliersResponse() {
        }
        
        public GetAllSuppliersResponse(CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSuppliersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CandyStore.Client.OrderServiceProxy.SupplierDto[] GetAllSuppliersResult;
        
        public GetAllSuppliersResponseBody() {
        }
        
        public GetAllSuppliersResponseBody(CandyStore.Client.OrderServiceProxy.SupplierDto[] GetAllSuppliersResult) {
            this.GetAllSuppliersResult = GetAllSuppliersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsBySupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsBySupplier", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequestBody Body;
        
        public GetProductsBySupplierRequest() {
        }
        
        public GetProductsBySupplierRequest(CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsBySupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string supplierName;
        
        public GetProductsBySupplierRequestBody() {
        }
        
        public GetProductsBySupplierRequestBody(string supplierName) {
            this.supplierName = supplierName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsBySupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsBySupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponseBody Body;
        
        public GetProductsBySupplierResponse() {
        }
        
        public GetProductsBySupplierResponse(CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsBySupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CandyStore.Client.OrderServiceProxy.ProductDto[] GetProductsBySupplierResult;
        
        public GetProductsBySupplierResponseBody() {
        }
        
        public GetProductsBySupplierResponseBody(CandyStore.Client.OrderServiceProxy.ProductDto[] GetProductsBySupplierResult) {
            this.GetProductsBySupplierResult = GetProductsBySupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByCustomer", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequestBody Body;
        
        public GetOrdersByCustomerRequest() {
        }
        
        public GetOrdersByCustomerRequest(CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CandyStore.Client.OrderServiceProxy.CustomerDto customer;
        
        public GetOrdersByCustomerRequestBody() {
        }
        
        public GetOrdersByCustomerRequestBody(CandyStore.Client.OrderServiceProxy.CustomerDto customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponseBody Body;
        
        public GetOrdersByCustomerResponse() {
        }
        
        public GetOrdersByCustomerResponse(CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CandyStore.Client.OrderServiceProxy.OrderDto[] GetOrdersByCustomerResult;
        
        public GetOrdersByCustomerResponseBody() {
        }
        
        public GetOrdersByCustomerResponseBody(CandyStore.Client.OrderServiceProxy.OrderDto[] GetOrdersByCustomerResult) {
            this.GetOrdersByCustomerResult = GetOrdersByCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrder", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.PlaceOrderRequestBody Body;
        
        public PlaceOrderRequest() {
        }
        
        public PlaceOrderRequest(CandyStore.Client.OrderServiceProxy.PlaceOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CandyStore.Client.OrderServiceProxy.CustomerDto customer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string supplierName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CandyStore.Client.OrderServiceProxy.ProductDto[] products;
        
        public PlaceOrderRequestBody() {
        }
        
        public PlaceOrderRequestBody(CandyStore.Client.OrderServiceProxy.CustomerDto customer, string supplierName, CandyStore.Client.OrderServiceProxy.ProductDto[] products) {
            this.customer = customer;
            this.supplierName = supplierName;
            this.products = products;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CandyStore.Client.OrderServiceProxy.PlaceOrderResponseBody Body;
        
        public PlaceOrderResponse() {
        }
        
        public PlaceOrderResponse(CandyStore.Client.OrderServiceProxy.PlaceOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PlaceOrderResponseBody {
        
        public PlaceOrderResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceSoapChannel : CandyStore.Client.OrderServiceProxy.OrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceSoapClient : System.ServiceModel.ClientBase<CandyStore.Client.OrderServiceProxy.OrderServiceSoap>, CandyStore.Client.OrderServiceProxy.OrderServiceSoap {
        
        public OrderServiceSoapClient() {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponse CandyStore.Client.OrderServiceProxy.OrderServiceSoap.GetAllSuppliers(CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest request) {
            return base.Channel.GetAllSuppliers(request);
        }
        
        public CandyStore.Client.OrderServiceProxy.SupplierDto[] GetAllSuppliers() {
            CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest inValue = new CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequestBody();
            CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponse retVal = ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).GetAllSuppliers(inValue);
            return retVal.Body.GetAllSuppliersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponse> CandyStore.Client.OrderServiceProxy.OrderServiceSoap.GetAllSuppliersAsync(CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest request) {
            return base.Channel.GetAllSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetAllSuppliersResponse> GetAllSuppliersAsync() {
            CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest inValue = new CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.GetAllSuppliersRequestBody();
            return ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).GetAllSuppliersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponse CandyStore.Client.OrderServiceProxy.OrderServiceSoap.GetProductsBySupplier(CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest request) {
            return base.Channel.GetProductsBySupplier(request);
        }
        
        public CandyStore.Client.OrderServiceProxy.ProductDto[] GetProductsBySupplier(string supplierName) {
            CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest inValue = new CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequestBody();
            inValue.Body.supplierName = supplierName;
            CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponse retVal = ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).GetProductsBySupplier(inValue);
            return retVal.Body.GetProductsBySupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponse> CandyStore.Client.OrderServiceProxy.OrderServiceSoap.GetProductsBySupplierAsync(CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest request) {
            return base.Channel.GetProductsBySupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetProductsBySupplierResponse> GetProductsBySupplierAsync(string supplierName) {
            CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest inValue = new CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.GetProductsBySupplierRequestBody();
            inValue.Body.supplierName = supplierName;
            return ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).GetProductsBySupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponse CandyStore.Client.OrderServiceProxy.OrderServiceSoap.GetOrdersByCustomer(CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest request) {
            return base.Channel.GetOrdersByCustomer(request);
        }
        
        public CandyStore.Client.OrderServiceProxy.OrderDto[] GetOrdersByCustomer(CandyStore.Client.OrderServiceProxy.CustomerDto customer) {
            CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest inValue = new CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequestBody();
            inValue.Body.customer = customer;
            CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponse retVal = ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).GetOrdersByCustomer(inValue);
            return retVal.Body.GetOrdersByCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponse> CandyStore.Client.OrderServiceProxy.OrderServiceSoap.GetOrdersByCustomerAsync(CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest request) {
            return base.Channel.GetOrdersByCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerResponse> GetOrdersByCustomerAsync(CandyStore.Client.OrderServiceProxy.CustomerDto customer) {
            CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest inValue = new CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.GetOrdersByCustomerRequestBody();
            inValue.Body.customer = customer;
            return ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).GetOrdersByCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandyStore.Client.OrderServiceProxy.PlaceOrderResponse CandyStore.Client.OrderServiceProxy.OrderServiceSoap.PlaceOrder(CandyStore.Client.OrderServiceProxy.PlaceOrderRequest request) {
            return base.Channel.PlaceOrder(request);
        }
        
        public void PlaceOrder(CandyStore.Client.OrderServiceProxy.CustomerDto customer, string supplierName, CandyStore.Client.OrderServiceProxy.ProductDto[] products) {
            CandyStore.Client.OrderServiceProxy.PlaceOrderRequest inValue = new CandyStore.Client.OrderServiceProxy.PlaceOrderRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.PlaceOrderRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.supplierName = supplierName;
            inValue.Body.products = products;
            CandyStore.Client.OrderServiceProxy.PlaceOrderResponse retVal = ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).PlaceOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.PlaceOrderResponse> CandyStore.Client.OrderServiceProxy.OrderServiceSoap.PlaceOrderAsync(CandyStore.Client.OrderServiceProxy.PlaceOrderRequest request) {
            return base.Channel.PlaceOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandyStore.Client.OrderServiceProxy.PlaceOrderResponse> PlaceOrderAsync(CandyStore.Client.OrderServiceProxy.CustomerDto customer, string supplierName, CandyStore.Client.OrderServiceProxy.ProductDto[] products) {
            CandyStore.Client.OrderServiceProxy.PlaceOrderRequest inValue = new CandyStore.Client.OrderServiceProxy.PlaceOrderRequest();
            inValue.Body = new CandyStore.Client.OrderServiceProxy.PlaceOrderRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.supplierName = supplierName;
            inValue.Body.products = products;
            return ((CandyStore.Client.OrderServiceProxy.OrderServiceSoap)(this)).PlaceOrderAsync(inValue);
        }
        
        public void CloseOrder(int orderId) {
            base.Channel.CloseOrder(orderId);
        }
        
        public System.Threading.Tasks.Task CloseOrderAsync(int orderId) {
            return base.Channel.CloseOrderAsync(orderId);
        }
    }
}
